<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=900" />
    <title>Screenshotgun</title>

    <? foreach ($this->_meta as $property => $content): ?>
        <meta name="<?= $property; ?>"
              property="<?= $property; ?>"
              content="<?= $content; ?>" />
    <? endforeach; ?>

    <link href="http://fonts.googleapis.com/css?family=Roboto:400,300&subset=latin,cyrillic" rel="stylesheet" />
    <link href="/css/style.css" rel="stylesheet" />

    <script src="/js/app.js"></script>
</head>

<body class="page page-<?= $this->_registry->router->getController(); ?>-<?= $this->_registry->router->getAction(); ?>">
    <? $this->content(); ?>
</body>
</html>
