<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Screenshotgun</title>

    <link href="http://fonts.googleapis.com/css?family=Roboto:400,300&subset=latin,cyrillic" rel="stylesheet" />
    <link href="/css/style.css" rel="stylesheet" />
</head>

<body class="page page-<?= $this->_registry->router->getController(); ?>-<?= $this->_registry->router->getAction(); ?>">
    <? $this->content(); ?>
</body>
</html>
