<div class="background-wrapper">
    <div class="background"></div>
</div>

<div class="page-content">
    <div class="header">
        Download the Alpha Version for <a href="/dist/ScreenshotgunInstaller.exe">Windows</a> or for <a href="https://github.com/ismd/screenshotgun#install">Linux</a>
    </div>

    <div class="rect">
        <div class="logo"></div>

        <div class="text-info">
            Coming soon!<br />
            Open screenshoter with cloud support and server part.
        </div>

        <div class="app"></div>
    </div>

    <div class="clearfix footer">
        <div class="bottom-description">
            Just for shooting screenshots and nothing more
        </div>

        <div class="mail-and-donate">
            &copy;
            Screenshotgun
            <?= (new DateTime)->format('Y'); ?>.
            <a href="mailto:ismd@screenshotgun.com">Mail us</a>
            <!--or
            <a href="javascript:void(0)">buy a beer</a>.-->
        </div>
    </div>
</div>
